# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_cuit_alter_proveedor_numero'),
        ('servicios_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomensual',
            name='proveedor',
            field=models.OneToOneField(db_column='cuit', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proveedores.proveedor'),
        ),
    ]
