# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consorcio',
            name='cuit',
            field=models.CharField(db_column='cuit', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Error de validación: CUIT debe contener solo dígitos.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='interes_por_mora',
            field=models.DecimalField(db_column='interes_por_mora', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Error de validación: Interés por mora debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='numero',
            field=models.PositiveIntegerField(db_column='numero', validators=[django.core.validators.MinValueValidator(1, message='Error de validación: Número debe ser mayor o igual a 1.'), django.core.validators.MaxValueValidator(59999, message='Error de validación: Número debe ser menor o igual a 59999.')]),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='redondeo_aumento',
            field=models.DecimalField(db_column='redondeo_aumento', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Error de validación: Redondeo de aumento debe ser mayor o igual a 0.')]),
        ),
    ]
