# Generated by Django 6.0.3 on 2026-04-01 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consorcios', to='usuarios.usuario'),
        ),
    ]
