# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='dni',
            field=models.CharField(db_column='dni', max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Error de validación: DNI debe contener solo dígitos.', regex='^\\d+$')]),
        ),
    ]
