# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratula', '0001_initial'),
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratula',
            name='consorcio',
            field=models.ForeignKey(db_column='cuit_consorcio', on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio'),
        ),
    ]
