# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
        ('propietarios', '0002_alter_propietario_dni'),
        ('unidades_funcionales', '0003_update_tipo_unidad_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadfuncional',
            name='consorcio',
            field=models.ForeignKey(db_column='cuit_consorcio', on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio'),
        ),
        migrations.AlterField(
            model_name='unidadfuncional',
            name='propietario',
            field=models.ForeignKey(db_column='dni_propietario', on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario'),
        ),
        migrations.AlterField(
            model_name='unidadfuncional',
            name='superficie',
            field=models.DecimalField(db_column='superficie', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Error de validación: Superficie debe ser mayor o igual a 0.01.')]),
        ),
        migrations.AlterField(
            model_name='unidadfuncional',
            name='tipo_de_unidad',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Lote', 'Lote'), ('PH', 'PH')], db_column='tipo_de_unidad', max_length=50),
        ),
    ]
