# Generated by Django 5.2.12 on 2026-03-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_funcionales', '0004_alter_unidadfuncional_consorcio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfuncional',
            name='coeficiente',
            field=models.DecimalField(blank=True, db_column='coeficiente', decimal_places=4, max_digits=6, null=True),
        ),
    ]
