# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
        ('gastos', '0001_initial'),
        ('proveedores', '0002_alter_proveedor_cuit_alter_proveedor_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='consorcio',
            field=models.ForeignKey(db_column='cuit_consorcio', on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(db_column='monto', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Error de validación: Monto debe ser mayor o igual a 0.01.')]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(db_column='cuit_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
