# Generated by Django 5.2.12 on 2026-03-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensas', '0002_alter_expensatemplate_consorcio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionexpensa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_EDICION', 'En edición'), ('CERRADA', 'Cerrada')], db_column='estado', default='BORRADOR', max_length=20),
        ),
    ]
