# Generated by Django 6.0.3 on 2026-04-01 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(db_column='correo_electronico', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('contrasena', models.CharField(db_column='contrasena', max_length=128)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, db_column='ultimo_ingreso', null=True)),
                ('esta_activo', models.BooleanField(db_column='esta_activo', default=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['apellido', 'nombre', 'correo_electronico'],
            },
        ),
    ]
