# Generated by Django 6.0.3 on 2026-04-01 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now, editable=False),
        ),
    ]
