# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
        ('pagos', '0002_estado_pago'),
        ('propietarios', '0002_alter_propietario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='consorcio',
            field=models.ForeignKey(db_column='cuit_consorcio', on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(db_column='monto', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Error de validación: Monto debe ser mayor o igual a 0.01.')]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='propietario',
            field=models.ForeignKey(db_column='dni_propietario', on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario'),
        ),
    ]
