# Generated by Django 5.2.12 on 2026-03-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_consorcio_alter_pago_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_pdf',
            field=models.FileField(blank=True, db_column='comprobante_pdf', null=True, upload_to='comprobantes/'),
        ),
    ]
