# Generated by Django 5.2.12 on 2026-03-11 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_cuit_and_more'),
        ('saldo_mensual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldomensual',
            name='consorcio',
            field=models.ForeignKey(db_column='cuit_consorcio', on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio'),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='saldo_inicial',
            field=models.DecimalField(db_column='saldo_inicial', decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Error de validación: Saldo inicial debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='total_gastos',
            field=models.DecimalField(db_column='total_gastos', decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Error de validación: Total gastos debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='total_pagos',
            field=models.DecimalField(db_column='total_pagos', decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Error de validación: Total pagos debe ser mayor o igual a 0.')]),
        ),
    ]
