name: Deploy Staging

on:
  push:
    branches:
      - 9-integracion-produccion-zonejs-expensas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deploy
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
          --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
